# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  apiback:
    image: apiback
    build:
      context: .
      dockerfile: apiback/Dockerfile
    ports:
      - 5010:5010
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
